name: PR Test

on:
    pull_request:
        branches: [dev]

jobs:
    lint:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x]

        steps:
            - name: Checkout branch
              uses: actions/checkout@v2

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - run: |
                  yarn install
                  yarn test
                  yarn lint
